# .streamlit/secrets.toml
# Copy this file, fill in your values, and NEVER commit the real file to git.

SUPABASE_URL      = "postgresql://postgres:UoF0CNIkONBbF3jk@db.dvhmdvejtbdmvfneirvs.supabase.co:5432/postgres"
SUPABASE_ANON_KEY = "UoF0CNIkONBbF3jk"
